_target_: fingerspelling_trainer.training.utils.alphabets.Alphabet
alphabet:
  A: 1
  B: 2
  C: 3
  CH: 4
  D: 5
  E: 6
  F: 7
  G: 8
  H: 9
  I: 10
  J: 11
  K: 12
  L: 13
  LL: 14
  M: 15
  N: 16
  Ñ: 17
  O: 18
  P: 19
  Q: 20
  R: 21
  RR: 22
  S: 23
  T: 24
  U: 25
  V: 26
  W: 27
  X: 28
  Y: 29
  Z: 30
  "@": 31
  # "_": 32 # keep this removed if not including spaces