obj:
  _target_: fingerspelling_trainer.training.models.lstm.LSTMTranslator
  model_cfg:
    add_velocity: false
    lstm:
      hidden_dim: 128
      num_layers: 2
      rnn_dropout: 0.25
      bidirectional: true
    mlp:
      hidden_dim: 128
      dropout: 0.25

